[tool.poetry]
name = "monterey-poetry-test"
version = "0.1.0"
description = ""
authors = ["foo <foo@bar.com>"]

[tool.poetry.dependencies]
python = "^3.9"
isort = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
